### ISSUE TITLE
MathJax - not cleaned from &amp; etc.

### ISSUE THREAD

**Issue by marcinofulus** [vbraun/ExportSageNB#4]
I have &amp; inside latex equations which were originally used for eqs. alignment ... & =&...
also some html tags like <br> were left inside $$ $$

**Comment by vbraun** [comment]
Do you have a minimal test, preferrably one per issue?

**Comment by marcinofulus** [comment]
[MathJax_problem1.zip](https://github.com/vbraun/ExportSageNB/files/341295/MathJax_problem1.zip)

**Comment by vbraun** [comment]
Fixed in da5aafd3b264e70f16ddfc96bff510f8c5a0d832
