### ISSUE TITLE
utf-8 in worksheet names

### ISSUE THREAD

**Issue by marcinofulus** [vbraun/ExportSageNB#5]
Unfortunately people use all possible strange charssets in worksheet names etc. 

I have strange effect where:

 sagenb-export --list

works and gives list with i18n chars

but
 sagenb-export --list > file fails with 

'ascii' codec can't encode character u'\u0142' in position 23: ordinal not in range(128)
btw: LC_ALL are set tu utf8

I have changes in sagenb_reader, open to io.open with utf-8 encoding explicitely, but it gave me:

UnicodeDecodeError: 'utf8' codec can't decode byte 0xf3 in position 368: invalid continuation byte

The problematic conf file contained indeen some junk:

VWDI projekt - R�\u017cankowski, Kie\u0142pi\u0144ski, Kozok

**Comment by vbraun** [comment]
Did you try with c1f96338cac44195eff86ba8bcbef66c229f9d11?

**Comment by marcinofulus** [comment]
yes "u" is in my snapshot. 

But the problem looks like there is "more" than utf8 ;-), Some people do not hesitate to use windows encodings as names of files, worksheets etc...

**Comment by marcinofulus** [comment]
plz have a look at the pickle that io.open did not liked:

[bad.pickle.zip](https://github.com/vbraun/ExportSageNB/files/341420/bad.pickle.zip)

**Comment by vbraun** [comment]
Fixed in 1036c9a60efdddb875d73f1dad0a43e3f56f2d1b
